In [ ]:
import pandas as pd

file_path = r"E:\pythonProgram\Spillover\database\tweets\tweets.csv"
df = pd.read_csv(file_path)
# 按time字段排序
df = df.sort_values(by="time")
# 重新保存文件
df.to_csv(file_path, index=False)

In [7]:
import pandas as pd

# 读取数据
file_path = r"E:\pythonProgram\Spillover\database\tweets\tweets.csv"
df = pd.read_csv(file_path)

# 转换 'time' 列为 datetime 格式，假设 'time' 列是字符串类型
df['time'] = pd.to_datetime(df['time'], format='%Y%m%d%H%M')
df = df[['time','id','text','isRetweet','isDeleted','device','favorites','retweets','isFlagged']]


# 定义日期范围
start_date_1 = pd.to_datetime('2017-01-20 00:00:00')
end_date_1 = pd.to_datetime('2021-01-20 00:00:00')

start_date_2 = pd.to_datetime('2021-01-20 00:00:00')
end_date_2 = pd.to_datetime('2025-01-20 00:00:00')

start_date_3 = pd.to_datetime('2025-01-20 00:00:00')
end_date_3 = pd.to_datetime('2025-03-14 12:00:00')

# 按照日期范围进行分割
df_first_term = df[(df['time'] >= start_date_1) & (df['time'] < end_date_1)]
df_interim_term = df[(df['time'] >= start_date_2) & (df['time'] < end_date_2)]
df_second_term = df[(df['time'] >= start_date_3) & (df['time'] <= end_date_3)]


df_first_term['time'] = df_first_term['time']
df_interim_term['time'] = df_interim_term['time']
df_second_term['time'] = df_second_term['time']
print(df_first_term.head())
print(df_interim_term.head())  
print(df_second_term.head())

# 保存为新的CSV文件
df_first_term.to_csv(r"E:\pythonProgram\Spillover\database\tweets\tweets_first_term.csv", index=False)
df_interim_term.to_csv(r"E:\pythonProgram\Spillover\database\tweets\tweets_interim_term.csv", index=False)
df_second_term.to_csv(r"E:\pythonProgram\Spillover\database\tweets\tweets_second_term.csv", index=False)

print("三个CSV文件已经成功保存。")

                 time            id  \
0 2017-01-20 00:40:00  8.222420e+17
1 2017-01-20 12:31:00  8.224210e+17
2 2017-01-20 17:51:00  8.225020e+17
3 2017-01-20 17:51:00  8.225020e+17
4 2017-01-20 17:52:00  8.225020e+17

                                                text isRetweet isDeleted  \
0  Thank you for joining us at the Lincoln Memori...         f         f
1  It all begins today! I will see you at 11:00 A...         f         f
2  power from Washington, D.C. and giving it back...         f         f
3  Today we are not merely transferring power fro...         f         f
4  What truly matters is not which party controls...         f         f

                device  favorites  retweets isFlagged
0   Twitter for iPhone     144912     28556         f
1  Twitter for Android     232628     57772         f
2   Twitter for iPhone      78281     14880         f
3   Twitter for iPhone      94860     16452         f
4   Twitter for iPhone     157266     35758         f
Empty DataFrame
Columns: [time, id, text, isRetweet, isDeleted, device, favorites, retweets, isFlagged]
Index: []
Empty DataFrame
Columns: [time, id, text, isRetweet, isDeleted, device, favorites, retweets, isFlagged]
Index: []
三个CSV文件已经成功保存。

In [14]:
import pandas as pd

# 读取CSV文件，指定分隔符为";"
df = pd.read_csv(r"D:\database\spillover\gc-1m.csv", header=None, delimiter=";")
df.tail(10)

                  0         1       2       3       4       5   6
6141783  11/03/2025  23:51:00  2920.7  2920.9  2920.7  2920.9   5
6141784  11/03/2025  23:52:00  2920.9  2921.4  2920.9  2921.4  11
6141785  11/03/2025  23:53:00  2921.3  2921.3  2920.9  2921.2  14
6141786  11/03/2025  23:54:00  2920.9  2921.1  2920.9  2921.1   3
6141787  11/03/2025  23:55:00  2921.1  2921.1  2921.1  2921.1   1
6141788  11/03/2025  23:56:00  2921.0  2921.1  2920.7  2920.7  13
6141789  11/03/2025  23:57:00  2920.7  2920.7  2920.7  2920.7   1
6141790  11/03/2025  23:58:00  2920.6  2920.6  2920.5  2920.5   3
6141791  11/03/2025  23:59:00  2920.2  2920.3  2920.1  2920.3  11
6141792  12/03/2025  00:00:00  2920.3  2920.7  2919.5  2919.5  36

In [2]:
import pandas as pd

# 读取CSV文件，指定分隔符为";"
df = pd.read_csv(r"D:\database\spillover\gc-1m.csv", header=None, delimiter=";")

# 合并前两个数据为time，格式为YYMMDDHHMM
df['time'] = pd.to_datetime(df[0].astype(str) + df[1].astype(str), format='%d/%m/%Y%H:%M:%S')

# 设置列名
df.columns = ['Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'time']

# 按时间排序
df = df.sort_values(by='time')

# 保留精确到分钟的时间并向上取整
df['time'] = df['time'].dt.ceil('T')

# 只保留需要的列
df = df[['time', 'Open', 'High', 'Low', 'Close', 'Volume']]

# 删除无用的Date和Time列
df.to_csv(r"D:\database\spillover\gc_new.csv", index=False)

print(df.head())

C:\Users\Issac\AppData\Local\Temp\ipykernel_22456\680818564.py:16: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df['time'] = df['time'].dt.ceil('T')

                 time   Open   High    Low  Close  Volume
0 2007-04-01 17:00:00  671.1  671.2  671.0  671.0      33
1 2007-04-01 17:01:00  671.0  671.2  671.0  671.2      11
2 2007-04-01 17:02:00  671.0  671.0  671.0  671.0       9
3 2007-04-01 17:03:00  671.0  671.0  671.0  671.0       5
4 2007-04-01 17:04:00  671.1  671.1  671.1  671.1      15

In [3]:
import pandas as pd

# 从指定路径读取数据
df = pd.read_csv(r"D:\database\spillover\gc_new.csv")

# 确保time列是时间类型，并向上取整到最近的整分钟
df['time'] = pd.to_datetime(df['time'])

# 定义日期范围
start_date_1 = pd.to_datetime('2017-01-20 00:00:00')
end_date_1 = pd.to_datetime('2021-01-20 00:00:00')

start_date_2 = pd.to_datetime('2021-01-20 00:00:00')
end_date_2 = pd.to_datetime('2025-01-20 00:00:00')

start_date_3 = pd.to_datetime('2025-01-20 00:00:00')
end_date_3 = pd.to_datetime('2025-03-14 12:00:00')

# 筛选数据并保存到不同的文件

# 第一个任期
df_1 = df[(df['time'] >= start_date_1) & (df['time'] < end_date_1)]
df_1.to_csv(r"D:\database\spillover\gc_first_term.csv", index=False)

# 在野期
df_2 = df[(df['time'] >= start_date_2) & (df['time'] < end_date_2)]
df_2.to_csv(r"D:\database\spillover\gc_inactive_period.csv", index=False)

# 第二任期
df_3 = df[(df['time'] >= start_date_3) & (df['time'] <= end_date_3)]
df_3.to_csv(r"D:\database\spillover\gc_second_term.csv", index=False)

# 输出前三行检查
print(df_1.head())
print(df_2.head())
print(df_3.head())

                       time    Open    High     Low   Close  Volume
3268162 2017-01-20 00:00:00  1206.6  1207.1  1206.6  1207.0     153
3268163 2017-01-20 00:01:00  1206.9  1207.0  1206.9  1206.9      16
3268164 2017-01-20 00:02:00  1207.0  1207.0  1207.0  1207.0      20
3268165 2017-01-20 00:03:00  1207.0  1207.3  1207.0  1207.2      71
3268166 2017-01-20 00:04:00  1207.2  1207.3  1207.2  1207.3      58
                       time    Open    High     Low   Close  Volume
4678774 2021-01-20 00:00:00  1850.7  1850.8  1849.9  1850.4     108
4678775 2021-01-20 00:01:00  1850.4  1851.0  1850.4  1850.5      92
4678776 2021-01-20 00:02:00  1850.4  1850.5  1850.3  1850.3      29
4678777 2021-01-20 00:03:00  1850.2  1850.6  1850.0  1850.3      60
4678778 2021-01-20 00:04:00  1850.1  1850.6  1850.0  1850.5      51
                       time    Open    High     Low   Close  Volume
6091101 2025-01-20 00:00:00  2749.0  2749.0  2748.4  2748.6      24
6091102 2025-01-20 00:01:00  2748.7  2749.0  2748.3  2748.8      60
6091103 2025-01-20 00:02:00  2748.9  2749.6  2748.9  2749.6      84
6091104 2025-01-20 00:03:00  2749.5  2749.8  2749.1  2749.8      54
6091105 2025-01-20 00:04:00  2749.6  2749.9  2749.2  2749.2      88

In [9]:
import pandas as pd

# 读取数据
file_path = r"E:\pythonProgram\Spillover\database\gold\gc_second_term.csv"
df = pd.read_csv(file_path)

# 确保 time 列为 datetime 类型
df['time'] = pd.to_datetime(df['time'])

# 按日期分组
df['date'] = df['time'].dt.date  # 提取日期

# 进行聚合
daily_df = df.groupby('date').agg(
    Open=('Open', 'first'),  # 取当天最早时间的 Open
    Close=('Close', 'last'),  # 取当天最晚时间的 Close
    High=('High', 'max'),  # 取当天最高值
    Low=('Low', 'min'),  # 取当天最低值
    Volume=('Volume', 'sum')  # 取当天总成交量
).reset_index()

# 保存日级数据
output_path = r"E:\pythonProgram\Spillover\database\gold\gc_daily.csv"
daily_df.to_csv(output_path, index=False)

# 显示前几行数据
print(daily_df.head())

         date    Open   Close    High     Low  Volume
0  2025-01-20  2749.0  2743.8  2754.8  2715.6  109626
1  2025-01-21  2743.8  2772.0  2772.3  2725.5  140133
2  2025-01-22  2771.8  2760.7  2774.4  2758.7  121511
3  2025-01-23  2760.7  2782.2  2784.9  2741.0  160518
4  2025-01-24  2782.3  2777.4  2794.8  2775.7  107482